### ISSUE TITLE
Typo in the documentation for Lagrangian Formulation

### ISSUE THREAD

**Issue by IsitaRex** [cooper-org/cooper#38]
## Bug
There is a minus sign on the documentation of Lagrangian formulations which should not be there.

The Lagrange multipliers aim to maximize the Lagrangian (Boyd, $5.1). Therefore, 

The current file says that the multiplier maximizes -L instead.

https://github.com/cooper-org/cooper/blob/de1c6fec6aef68ca024c017e06812c3dd453e5c4/docs/source/lagrangian_formulation.rst#L42

## Steps

The minus sign should be erased, so that the explanation is mathematically correct.

## Expected behavior

Correct documentation.
No changes required in the source code.

## Environment

No environment needed.

## Context

Error on documentation

**Comment by juan43ramirez** [comment]
This is indeed a typo. Please feel free to correct it.
