### ISSUE TITLE
how to use cuda acceleration

### ISSUE THREAD

**Issue by Timbrer** [cooper-org/cooper#57]
Hi, I was wondering if cooper can use cuda to accelerate the computation. (I thought it could, but there is no place to claim something like probs.cuda() )

**Comment by juan43ramirez** [comment]
Yes, Cooper can benefit from Cuda acceleration. 

As long as your tensors and model are on Cuda, calculations will be carried out on GPUs. 
Cooper lets Pytorch handle the details.

Are you having specific issues using Cooper on Cuda? A trace or code snippet would be helpful.

**Comment by Timbrer** [comment]
Thanks for your reply.

I do not have errors, but I also do not find GPU is used when I run the code. 

Maybe beacause my problem is too simple.

**Comment by gallego-posada** [comment]
You can place your tensors on the GPU before or during the call to `closure`. For example, you can do something like this:

```python

model = model.cuda()

for batch_id, (input_, target_) in enumerate(train_loader):
    
    # Move desired tensors to the righ device.
    input_, target_ = input_.cuda(), target_.cuda()

    constrained_optimizer.zero_grad()
    lagrangian = formulation.composite_objective(cmp.closure, input_, target_, model ...)
    formulation.custom_backward(lagrangian)
    constrained_optimizer.step()

```

Cooper will automatically place the multipliers on the same device in which the constraint defects of the `CMPState` are located.
