### ISSUE TITLE
Cooper level wrappers for `formulation.custom_backward` and `formulation.composite_objective`

### ISSUE THREAD

**Issue by juan43ramirez** [cooper-org/cooper#58]
## Enhancement

Create wrappers `cooper.backward` for `formulation.custom_backward` and `cooper.compute_lagrangian` for `formulation.composite_objective`.

This would change the way a user interacts with Cooper. However, it does not represent a change in Cooper's back-end.

## Motivation

A cleaner pipeline for the user, where there is no need to access the methods of a formulation:

```python
for step in range(num_steps):
    ...
    constrained_optimizer.zero_grad()
    lagrangian = cooper.compute_lagrangian(formulation, ...)
    cooper.backward(formulation, lagrangian)
    constrained_optimizer.step()
``` 

As opposed to the current pipeline:

```python
for step in range(num_steps):
    ...
    constrained_optimizer.zero_grad()
    lagrangian = formulation.composite_objective(...)
    formulation.custom_backward(lagrangian)
    constrained_optimizer.step()
```

**Comment by gallego-posada** [comment]
I agree with the renaming of `custom_backward` to `backward`, but I would recommend this being a method of the formulation directly. Right now, the user might not have enough information from the `cooper.backward` docstring to know what arguments need to be provided in this call.

Maybe we can just remove `custom_backward` altogether, rename it to `backward` and make the call directly as a method of the `Formulation` object. 

Something similar would apply to the `compute_lagrangian` method.
