### ISSUE TITLE
Deprecated `StateLogger`

### ISSUE THREAD

**Issue by juan43ramirez** [cooper-org/cooper#61]
## Bug

The `StateLogger` in `cooper.utils.state_logger.py` is not compatible with the latest version of Cooper's dev branch. 

It assumes that a `Formulation` will have a `ConstrainedMinimizationProblem` as an attribute:

https://github.com/cooper-org/cooper/blob/3e0aa6fd80b2977936db8aae4affce78bb466379/cooper/utils/state_logger.py#L42-L48

This is not the case since merging #56.

## Steps

Update the interface of `StateLogger`. `store_metrics` should receive a `CMPState` or the unpacked metrics.

**Comment by gallego-posada** [comment]
Closed by #64
