### ISSUE TITLE
Non comprehensive `__init__` files

### ISSUE THREAD

**Issue by juan43ramirez** [cooper-org/cooper#65]
## Enhancement

`__init__` files throughout Cooper are not fully consistent.

For instance, `Cooper.__init__` imports `UnconstrainedFormulation` and `LagrangianFormulation` , but *not* `AugmentedLagrangianFormulation`.
https://github.com/cooper-org/cooper/blob/a8b3400fecbe9e6e8e5e8c4d49c7959623a0154e/cooper/__init__.py#L18-L22

For consistency, we should import the `AugmentedLagrangianFormulation` as well.

**Note**: Creating an issue as there may be other instances of this throughout the library.

**Comment by gallego-posada** [comment]
Good catch. I went over the other __init__ files and it seems like this was the only relevant import missing.
